-- Migration 070: Hilfetexte zur Absicherung riskanter Aktionen (Okt 2026).
-- Löschen eines ganzen Jahres (JM, Endschiessen, Heim, Kanti) sichert vorher die Datenbank und nennt
-- Jahr und Anzahl; Migrationen und Restore bieten «Vorher sichern» (standardmässig an); die
-- JM-Erfassung prüft die Maximalpunkte und speichert mit Enter im letzten Feld bzw. Ctrl+S.
-- Ersetzt für diese Schlüssel die Texte aus 068; diese Datei ist jetzt ihre Quelle der Wahrheit.
--
-- Idempotent: ON DUPLICATE KEY UPDATE.
-- Hinweis: keine Zeile innerhalb der Strings darf mit zwei Bindestrichen beginnen (Kommentar-Filter des Runners).

INSERT INTO hilfetexte (schluessel, titel, inhalt_html, kategorie) VALUES
('jmresultate.uebersicht',
 'Jahresmeisterschaft erfassen',
 '<p>Hier werden die Resultate der Jahresmeisterschaft erfasst. Jede Karte steht für einen Anlass des gewählten Jahres und zeigt, wie viele der aktiven Mitglieder bereits ein Resultat haben (grüner Rahmen = vollständig). Ein Klick auf die Karte öffnet rechts das Erfassungs-Panel.</p><ul><li><strong>Endstich</strong> und <strong>Bester Kantonalstich</strong> haben keine Karte: ihre Werte kommen automatisch aus dem Endschiessen bzw. dem Kantonalstich. Info-Einträge und Anlässe des erweiterten Programms erscheinen ebenfalls nicht.</li><li><strong>PDF importieren</strong> liest eine fremde Einzelrangliste (z.B. Vereinsstich) oder die FSA-Teilnehmerliste für Obligatorisch und Feldschiessen ein. Vereinsmitglieder werden automatisch erkannt, die Vorschau lässt sich korrigieren; bereits erfasste Zeilen sind gelb markiert und abgewählt. Die Ränge 1 bis 10 werden zusätzlich als Einzelrangierung gespeichert, eine erkannte Vereinszeile als Sektionsrangierung.</li><li><strong>Veröffentlichen</strong> erscheint, sobald gespeicherte Änderungen noch nicht für das Portal freigegeben sind (Zähler = offene Einträge), und macht sie dort sichtbar.</li><li><strong>Alle Resultate löschen</strong> entfernt sämtliche JM-Resultate des <em>gewählten</em> Jahres; Endschiessen und Kantonalstich bleiben unberührt. Die Rückfrage nennt Jahr und Anzahl. Vor dem Löschen wird automatisch eine Sicherung der ganzen Datenbank erstellt; sie steht danach auf der Seite <a href="backup_restore.php">Backup &amp; Restore</a> (Name beginnt mit «vorher_jm-loeschen»). Scheitert die Sicherung, wird nichts gelöscht.</li><li><strong>Rangliste</strong> wechselt zur Ranglisten-Seite; unten auf dieser Seite steht dieselbe Rangliste Kat. A und Kat. B als Kontrolle.</li></ul><p>Mitglieder können ihre Resultate des laufenden Jahres im Portal selbst melden; solche Einträge sind im Panel gelb als «gemeldet» markiert, bis der Vorstand sie speichert.</p>',
 'jmresultate'),

('jmresultate.erfassung',
 'Erfassungs-Panel eines Anlasses',
 '<p>Im Kopf stehen Anlass, Maximalpunkte und, falls gesetzt, das Kennzeichen «Streicher». Darunter alle aktiven Mitglieder, alphabetisch in zwei Gruppen: <strong>Mit JM-Resultat</strong> (hat in diesem Jahr irgendwo ein gewertetes Resultat; Obligatorisch, Feldschiessen, Sektionsmeisterschaft und Cup zählen dafür nicht) und <strong>Noch ohne JM-Resultat</strong>. Grün hinterlegte Zeilen haben in <em>diesem</em> Anlass ein Resultat.</p><ul><li>Punkte als ganze Zahl eingeben; <strong>Enter</strong> springt zum nächsten Feld, im letzten Feld speichert Enter. <strong>Ctrl+S</strong> speichert jederzeit. Das Suchfeld filtert die Liste. Ein geleertes Feld löscht das Resultat beim Speichern.</li><li>Werte über den Maximalpunkten oder keine gültige Zahl werden rot umrandet; der Hinweis erscheint beim Zeigen oder Fokussieren des Feldes. Gespeichert wird erst, wenn alle Felder stimmen.</li><li><strong>Sektionsmeisterschaft</strong> (grüner Kopf) hat zwei Felder R1 und R2; in der Rangliste zählt nur der höhere Wert.</li><li><strong>Endstich</strong> und <strong>Bester Kantonalstich</strong> sind reine Anzeige: Summe der zehn Schüsse bzw. beste Passe. Hier gibt es keinen Speichern-Knopf.</li><li>Gelb umrandete Felder mit «gemeldet» stammen von der Selbsteingabe im Portal. Mit dem Speichern des Anlasses gelten die gespeicherten Einträge als vom Vorstand bestätigt.</li></ul><p>Fortschritt und Zähler unten zeigen erfasst/total. Escape, Abbrechen oder ein Klick neben das Panel schliessen es; bei ungespeicherten Änderungen wird nachgefragt. Schlägt das Speichern fehl, bleiben die Eingaben im Panel stehen.</p>',
 'jmresultate'),

('heimresultate.aktionen',
 'Aktionen der Resultaterfassung',
 '<ul><li><strong>Schnellerfassung</strong> öffnet das Panel, in dem ein Schütze nach dem anderen erfasst wird (nur am Desktop sichtbar).</li><li><strong>Speichern</strong> schreibt alle Zeilen des Rasters. Leere Felder, auf die später noch ein Wert folgt, werden dabei automatisch mit 0 gefüllt; Mitglieder ohne einen einzigen Wert erhalten keinen Datensatz.</li><li><strong>Rangliste</strong> wechselt zur Heimmeisterschaft-Rangliste.</li><li><strong>Veröffentlichen</strong> legt nach Rückfrage einen Eintrag «Heimresultate JAHR aktualisiert» im Änderungsprotokoll an, das den Mitgliedern angezeigt wird. Die Resultate selbst sind unabhängig davon sofort in der Rangliste sichtbar.</li><li><strong>Alle Resultate löschen</strong> entfernt sämtliche Heimresultate des gewählten Jahres; die Rückfrage nennt Jahr und Anzahl. Vorher wird automatisch eine Sicherung der ganzen Datenbank erstellt (Seite <a href="backup_restore.php">Backup &amp; Restore</a>, Name beginnt mit «vorher_heim-loeschen»). Scheitert die Sicherung, wird nichts gelöscht.</li></ul>',
 'heimresultate'),

('kantiresultate.aktionen',
 'Aktionen der Resultaterfassung',
 '<ul><li><strong>Schnellerfassung</strong> öffnet das Panel, in dem ein Schütze nach dem anderen erfasst wird (nur am Desktop sichtbar).</li><li><strong>Speichern</strong> schreibt alle Zeilen des Rasters. Leere Felder, auf die später noch ein Wert folgt, werden dabei automatisch mit 0 gefüllt; Mitglieder ohne einen einzigen Wert erhalten keinen Datensatz.</li><li><strong>Rangliste</strong> wechselt zur Kantonalstich-Rangliste.</li><li><strong>Veröffentlichen</strong> legt nach Rückfrage einen Eintrag «Kantiresultate JAHR aktualisiert» im Änderungsprotokoll an, das den Mitgliedern angezeigt wird. Die Resultate selbst sind unabhängig davon sofort in der Rangliste sichtbar.</li><li><strong>Alle Resultate löschen</strong> entfernt sämtliche Kantonalstich-Resultate des gewählten Jahres; die Rückfrage nennt Jahr und Anzahl. Vorher wird automatisch eine Sicherung der ganzen Datenbank erstellt (Seite <a href="backup_restore.php">Backup &amp; Restore</a>, Name beginnt mit «vorher_kanti-loeschen»). Scheitert die Sicherung, wird nichts gelöscht.</li></ul>',
 'kantiresultate'),

('endresultate.uebersicht',
 'Endschiessen: Resultate erfassen',
 '<p>Hier werden die Resultate der <strong>Mitglieder</strong> am Endschiessen erfasst. Die Tabelle zeigt für das gewählte Jahr alle Mitglieder, die Stiche gelöst oder bereits Resultate haben, mit dem Total je Stich.</p><ul><li><strong>Zeile anklicken</strong> öffnet rechts das Erfassungs-Panel. Aktiv sind nur die Stiche, die das Mitglied unter «Endschiessen lösen» gelöst hat; nicht gelöste Stiche sind zusammengeklappt und mit «Nicht gelöst» markiert. Das Feld Absenden ist immer offen.</li><li>In der Tabelle steht <strong>«gelöst»</strong>, wenn ein Stich gelöst, aber noch kein Resultat erfasst ist; «–» heisst nicht gelöst.</li><li><strong>Werte</strong>: Endstich und Schwini pro Schuss 0–10, Kunst, Glück und Zabig als Hunderterwertung 0–100. Die Totale rechnen beim Tippen mit.</li><li><strong>Speichern &amp; Nächster</strong> springt zum nächsten Mitglied ohne Resultate; der Fortschrittsbalken zählt Mitglieder mit Resultaten.</li><li>Gespeichert wird ein Stich nur, wenn mindestens ein Wert grösser 0 ist; leere Stiche erzeugen keinen Eintrag.</li></ul><p><strong>Alle Resultate löschen</strong> entfernt sämtliche Endschiessen-Resultate des gewählten Jahres (Endstich, Schwini, Kunst, Glück, Zabig) und den zugehörigen Endstich-Eintrag der Jahresmeisterschaft. Die Rückfrage nennt Jahr und Anzahl Einträge; vorher wird automatisch eine Sicherung der ganzen Datenbank erstellt (Seite <a href="backup_restore.php">Backup &amp; Restore</a>, Name beginnt mit «vorher_endsch-loeschen»). Der Papierkorb im Panel löscht nur ein einzelnes Mitglied. Alternativ lassen sich Resultate aus der Imetron-CSV importieren (<a href="endsch_import.php">CSV-Import Endschiessen</a>); die Schüsse der Partnerinnen werden unter <a href="endresultate_partner.php">Partnerinnen erfassen</a> erfasst.</p>',
 'endresultate'),

('backup_restore.restore',
 'Wiederherstellen',
 '<p>Ein Restore ersetzt die <strong>gesamte</strong> Datenbank durch den Stand der Sicherung. Alles, was seit dieser Sicherung erfasst wurde, wird überschrieben.</p><ul><li>Quelle ist entweder eine Datei vom eigenen Rechner (gepackt oder ungepackt) oder eine Sicherung aus der Liste (Pfeil-Symbol).</li><li>In der Sicherheitsabfrage ist <strong>«Vorher eine Sicherung der aktuellen Datenbank erstellen»</strong> angehakt. So entsteht unmittelbar vor dem Restore ein Stand «vorher_restore…», mit dem sich der Restore selbst wieder zurücknehmen lässt. Scheitert diese Sicherung, wird nichts wiederhergestellt.</li><li>Der Vorgang kann einige Minuten dauern; das Fenster in dieser Zeit nicht schliessen.</li></ul><p>Bei einem Fehler zeigt das Fenster die Meldung und unter «Technische Details» die Ausgabe des Servers.</p>',
 'backup_restore'),

('backup_restore.liste',
 'Verfügbare Sicherungen',
 '<p>Alle Sicherungen auf dem Server, neueste zuerst, mit Grösse und Erstellzeit. Manuelle und nächtliche Sicherungen stehen in derselben Liste.</p><ul><li>Sicherungen, deren Name mit <strong>vorher_</strong> beginnt, entstehen automatisch unmittelbar vor einer riskanten Aktion: Löschen aller Resultate eines Jahres, Datenbank-Aktualisierung oder Restore. Der Name sagt, wovor gesichert wurde (z.B. «vorher_jm-loeschen-2025»). Davon bleiben die neuesten 10; die nächtlichen Sicherungen werden getrennt gezählt (die neuesten 14).</li><li><strong>Herunterladen</strong> speichert die gepackte Datei lokal, etwa zur Aufbewahrung oder für einen späteren Restore aus Datei.</li><li><strong>Wiederherstellen</strong> spielt genau diesen Stand ein (siehe Hilfe bei «Restore»).</li><li><strong>Löschen</strong> entfernt die Datei nach Bestätigung endgültig vom Server.</li></ul>',
 'backup_restore'),

('aktualisierung.ausstehend',
 'Ausstehende Migrationen ausführen',
 '<p><strong>Ausstehende ausführen</strong> wendet alle gelisteten Dateien nacheinander in Nummernreihenfolge an. In der Rückfrage ist <strong>«Vorher eine Sicherung der Datenbank erstellen»</strong> angehakt: Vor dem ersten Schritt entsteht ein Stand «vorher_migration…» auf der Seite <a href="../inc/backup_restore.php">Backup &amp; Restore</a>, mit dem sich der Lauf zurücknehmen lässt. Scheitert die Sicherung, wird keine Migration ausgeführt. Das Ergebnis erscheint oben auf der Seite.</p><ul><li>Grün: die erfolgreich angewendeten Dateien; sie wandern nach «Bereits angewendet».</li><li>Rot: der Fehler, bei dem der Lauf <strong>abgebrochen</strong> wurde. Die fehlerhafte Datei und alle folgenden bleiben ausstehend; bereits erfolgreiche Dateien davor sind vermerkt.</li></ul><p>Nach einem Fehler zuerst die Meldung prüfen (meist eine Spalte, die schon existiert, oder ein Tippfehler in der Datei), die Datei korrigieren lassen und den Lauf wiederholen. Der Knopf fehlt, solange die Baseline noch nicht gesetzt ist.</p>',
 'aktualisierung')

ON DUPLICATE KEY UPDATE
    titel         = VALUES(titel),
    inhalt_html   = VALUES(inhalt_html),
    kategorie     = VALUES(kategorie),
    ist_geloescht = 0;
