-- Migration 073: Hilfetexte nach dem Umbau der Erfassungsseiten (Okt 2026):
-- Heimmeisterschaft und Kantonalstich (Kopf-Card, Filter, Suche, Tasten, ungespeicherte Zeilen,
-- Schnellerfassung im neuen Panel) sowie Endschiessen Partnerinnen (Stand, Filter, Gäste,
-- kein Löschen ganzer Jahre mehr). Die Schlüssel *.aktionen entfallen, weil die Aktionen jetzt
-- in der Kopf-Card stehen und in der Übersicht erklärt werden.
--
-- Idempotent: ON DUPLICATE KEY UPDATE bzw. UPDATE auf feste Schlüssel.
-- Hinweis: keine Zeile innerhalb der Strings darf mit zwei Bindestrichen beginnen (Kommentar-Filter des Runners).

INSERT INTO hilfetexte (schluessel, titel, inhalt_html, kategorie) VALUES
('heimresultate.uebersicht',
 'Heimmeisterschaft: Resultate erfassen',
 '<p>Hier werden die Resultate der <strong>Heimmeisterschaft</strong> eines Jahres erfasst: pro Mitglied bis zu <strong>acht Passen</strong> mit je höchstens 100 Punkten. Das Total rechnet die Seite laufend mit.</p><ul><li><strong>Oben</strong> stehen das Jahr, wie viele Mitglieder Resultate haben und wie viele alle acht Passen. Ist nicht das laufende Jahr gewählt, steht daneben «Archiv JAHR» mit einem Knopf zurück.</li><li><strong>Liste</strong>: alle aktiven Mitglieder, zuerst die mit Resultaten, dann die ohne. Filter (Alle, Mit Resultaten, Ohne) und Suche grenzen sie ein.</li><li>Erfasst wird direkt im <strong>Raster</strong> oder in der <strong>Schnellerfassung</strong> (Schütze um Schütze, nur am Desktop). Auf dem Handy erscheint pro Mitglied eine aufklappbare Karte.</li><li><strong>Speichern</strong> (auch Ctrl+S) schreibt alle Zeilen des Rasters. Noch nicht gespeicherte Zeilen tragen einen blauen Punkt hinter dem Namen und werden oben gezählt; vor einem Jahreswechsel fragt die Seite nach, beim Verlassen warnt der Browser.</li><li><strong>Veröffentlichen</strong> legt nach Rückfrage einen Eintrag «Heimresultate JAHR aktualisiert» im Änderungsprotokoll der Mitglieder an. Die Resultate selbst sind unabhängig davon sofort in der Rangliste sichtbar.</li><li>Kategorie A und B ergeben sich aus der Waffe in den Mitglieder-Stammdaten und wirken in der Rangliste (<a href="heimrang.php">Heimmeisterschaft Ranglisten</a>).</li></ul><p>Ganze Jahre werden nicht gelöscht; frühere Jahre bleiben über die Jahresauswahl abrufbar. Resultate aus der Auswertungsdatei der Schiessanlage lassen sich per CSV einlesen (<a href="heimkanti_import.php">CSV-Import Heim/Kanti</a>).</p>',
 'heimresultate'),

('heimresultate.tabelle',
 'Raster: Eingabe, Stand und Total',
 '<ul><li>Pro Passe sind nur ganze Zahlen bis 100 erlaubt; grössere Werte werden auf 100 begrenzt. Ausgefüllte Felder sind weiss, leere grau.</li><li><strong>Enter</strong> oder <strong>Tab</strong> springt ins nächste Feld, die Pfeiltasten <strong>auf</strong> und <strong>ab</strong> in dieselbe Passe der Zeile darüber oder darunter. So lässt sich eine Passe für alle Schützen nacheinander eintragen.</li><li>Neben dem Namen steht, wie viele Passen erfasst sind (etwa 3/8, grün bei allen acht). Ein Klick auf den Namen öffnet den Schützen in der Schnellerfassung.</li><li><strong>Total</strong> ist die Summe aller Passen; die Rangliste rechnet dieselbe Summe.</li><li>Beim Speichern werden bei bestehenden Datensätzen nur ausgefüllte Felder übernommen. Ein geleertes Feld löscht den gespeicherten Wert nicht; wer ein Resultat entfernen will, trägt 0 ein.</li><li>Leere Felder vor einer später ausgefüllten Passe werden beim Speichern zu 0 (nicht geschossen). Mitglieder ohne einen einzigen Wert erhalten keinen Datensatz.</li><li>Ein ungültiger Wert verhindert das Speichern ganz: die Meldung nennt ihn, und es wird nichts geändert.</li></ul>',
 'heimresultate'),

('heimresultate.schnellerfassung',
 'Schnellerfassung: Schütze um Schütze',
 '<p>Das Panel zeigt jeweils ein Mitglied mit grossen Eingabefeldern für alle acht Passen. Es ist eine andere Ansicht auf das Raster: jede Eingabe steht sofort auch in der Tabelle, das Total läuft mit.</p><ul><li><strong>Schütze wechseln</strong>: suchen oder auswählen; vollständig erfasste sind mit einem Häkchen markiert. Die Pfeile oben rechts blättern zum vorherigen oder nächsten Mitglied.</li><li><strong>Enter</strong> springt zum nächsten Feld, im letzten Feld wird gespeichert und weitergeblättert. Nach zwei Ziffern (beginnt die Zahl mit 1, nach drei) springt die Eingabe von selbst weiter.</li><li><strong>Speichern</strong> (Ctrl+S) sichert nur diesen Schützen und schliesst das Panel. <strong>Speichern &amp; Weiter</strong> (Ctrl+Enter) springt danach zum nächsten Mitglied, dem noch Passen fehlen. <strong>Escape</strong> schliesst ohne Speichern.</li><li>Leere Felder vor einer späteren Passe werden als 0 gespeichert.</li></ul><p>Was im Panel nicht gespeichert wurde, bleibt im Raster als ungespeichert markiert und wird mit «Speichern» oben mitgesichert.</p>',
 'heimresultate'),

('kantiresultate.uebersicht',
 'Kantonalstich: Resultate erfassen',
 '<p>Hier werden die Resultate des <strong>Kantonalstichs</strong> eines Jahres erfasst: pro Mitglied bis zu <strong>fünf Passen</strong>. Passe 1 gilt als Hauptdoppel, die Passen 2 bis 5 als Nachdoppel; so werden sie in der Kantonalstich-Rangliste und der SKSG-Abrechnung geführt.</p><ul><li><strong>Oben</strong> stehen das Jahr, wie viele Mitglieder Resultate haben und wie viele alle fünf Passen. Ist nicht das laufende Jahr gewählt, steht daneben «Archiv JAHR» mit einem Knopf zurück.</li><li><strong>Liste</strong>: alle aktiven Mitglieder, zuerst die mit Resultaten, dann die ohne. Filter (Alle, Mit Resultaten, Ohne) und Suche grenzen sie ein.</li><li>Erfasst wird direkt im <strong>Raster</strong> oder in der <strong>Schnellerfassung</strong> (Schütze um Schütze, nur am Desktop). Auf dem Handy erscheint pro Mitglied eine aufklappbare Karte.</li><li><strong>Speichern</strong> (auch Ctrl+S) schreibt alle Zeilen des Rasters. Noch nicht gespeicherte Zeilen tragen einen blauen Punkt hinter dem Namen und werden oben gezählt; vor einem Jahreswechsel fragt die Seite nach, beim Verlassen warnt der Browser.</li><li><strong>Veröffentlichen</strong> legt nach Rückfrage einen Eintrag «Kantiresultate JAHR aktualisiert» im Änderungsprotokoll der Mitglieder an. Die Resultate selbst sind unabhängig davon sofort in der Rangliste sichtbar.</li><li>Kategorie A und B ergeben sich aus der Waffe in den Mitglieder-Stammdaten und wirken in der Rangliste (<a href="kantirang.php">Kantonalstich Ranglisten</a>) sowie in der Abrechnung (<a href="kantiabr.php">Kantonalstich Ranglisten und Abrechnung</a>).</li></ul><p>Ganze Jahre werden nicht gelöscht; frühere Jahre bleiben über die Jahresauswahl abrufbar. Resultate aus der Auswertungsdatei der Schiessanlage lassen sich per CSV einlesen (<a href="heimkanti_import.php">CSV-Import Heim/Kanti</a>).</p>',
 'kantiresultate'),

('kantiresultate.tabelle',
 'Raster: Eingabe, Stand und Total',
 '<ul><li>Pro Passe sind nur ganze Zahlen bis 100 erlaubt. Ausgefüllte Felder sind weiss, leere grau; die <strong>beste Passe</strong> eines Schützen ist blau hervorgehoben (in der Schnellerfassung mit «beste» beschriftet).</li><li><strong>Enter</strong> oder <strong>Tab</strong> springt ins nächste Feld, die Pfeiltasten <strong>auf</strong> und <strong>ab</strong> in dieselbe Passe der Zeile darüber oder darunter.</li><li>Neben dem Namen steht, wie viele Passen erfasst sind (etwa 2/5, grün bei allen fünf). Ein Klick auf den Namen öffnet den Schützen in der Schnellerfassung.</li><li><strong>Total</strong> ist die Summe aller Passen; die Rangliste rechnet dieselbe Summe.</li><li>Beim Speichern werden bei bestehenden Datensätzen nur ausgefüllte Felder übernommen. Ein geleertes Feld löscht den gespeicherten Wert nicht; wer ein Resultat entfernen will, trägt 0 ein.</li><li>Leere Felder vor einer später ausgefüllten Passe werden beim Speichern zu 0 (nicht geschossen). Mitglieder ohne einen einzigen Wert erhalten keinen Datensatz.</li><li>Ein ungültiger Wert verhindert das Speichern ganz: die Meldung nennt ihn, und es wird nichts geändert.</li></ul>',
 'kantiresultate'),

('kantiresultate.schnellerfassung',
 'Schnellerfassung: Schütze um Schütze',
 '<p>Das Panel zeigt jeweils ein Mitglied mit grossen Eingabefeldern für die fünf Passen. Es ist eine andere Ansicht auf das Raster: jede Eingabe steht sofort auch in der Tabelle, das Total läuft mit, die beste Passe ist mit «beste» beschriftet.</p><ul><li><strong>Schütze wechseln</strong>: suchen oder auswählen; vollständig erfasste sind mit einem Häkchen markiert. Die Pfeile oben rechts blättern zum vorherigen oder nächsten Mitglied.</li><li><strong>Enter</strong> springt zum nächsten Feld, im letzten Feld wird gespeichert und weitergeblättert.</li><li><strong>Speichern</strong> (Ctrl+S) sichert nur diesen Schützen und schliesst das Panel. <strong>Speichern &amp; Weiter</strong> (Ctrl+Enter) springt danach zum nächsten Mitglied, dem noch Passen fehlen. <strong>Escape</strong> schliesst ohne Speichern.</li><li>Leere Felder vor einer späteren Passe werden als 0 gespeichert.</li></ul><p>Was im Panel nicht gespeichert wurde, bleibt im Raster als ungespeichert markiert und wird mit «Speichern» oben mitgesichert.</p>',
 'kantiresultate'),

('endresultate_partner.uebersicht',
 'Endschiessen: Partnerinnen erfassen',
 '<p>Hier werden die Resultate der <strong>Partnerinnen</strong> erfasst, die ein Mitglied ans Endschiessen mitbringt. Pro Mitglied und Jahr gibt es einen Eintrag mit Endstich, Sie-und-Er-Anteil und Partner Schwini.</p><ul><li><strong>Stand</strong>: «offen» (Zeile gelb), solange eine Partnerin noch keine Resultate hat, sonst «erfasst». Oben stehen Fortschritt und Zähler; Filter (Alle, Offen, Erfasst) und Suche grenzen die Liste ein.</li><li><strong>Gast</strong>: Gäste aus dem Lösen, für die noch kein Eintrag besteht, stehen mit der Marke «Gast» in der Liste. Ein Klick öffnet einen neuen Eintrag mit vorausgefülltem Namen; das Mitglied wird dazu gewählt.</li><li><strong>Partnerin hinzufügen</strong> öffnet ein leeres Panel: Mitglied wählen und Namen eingeben (beides Pflicht), Schüsse eintragen, speichern. Eine Zeile anklicken (oder mit den Pfeiltasten wählen und Enter) öffnet den bestehenden Eintrag.</li><li>Werte 0–10, Zehntel sind erlaubt; Werte ausserhalb werden als 0 gespeichert.</li><li>In der Spalte «Sie und Er» stehen die Punkte der Partnerin rot und die des Mitglieds blau; die Schüsse des Mitglieds werden unter <a href="endresultate.php">Endschiessen Resultaterfassung</a> erfasst.</li><li><strong>Speichern &amp; nächste offene</strong> (auch Ctrl+Enter) speichert und öffnet die nächste Partnerin ohne Resultate, Ctrl+S speichert.</li></ul><p><strong>Löschen</strong> im Panel entfernt den ganzen Eintrag, also auch die Sie-und-Er-Schüsse 6–10 des Mitglieds. Ganze Jahre werden nicht gelöscht; frühere Jahre bleiben über die Jahresauswahl abrufbar. Ein Eintrag mit dem Namen «Partner» wurde vom Sie-und-Er-Erfassen oder vom CSV-Import als Platzhalter angelegt und wartet auf den richtigen Namen. Ranglisten: «Partner» und «Sie &amp; Er» unter <a href="endschrang.php">Endschiessen Ranglisten</a>.</p>',
 'endresultate_partner')

ON DUPLICATE KEY UPDATE
    titel         = VALUES(titel),
    inhalt_html   = VALUES(inhalt_html),
    kategorie     = VALUES(kategorie),
    ist_geloescht = 0;

UPDATE hilfetexte SET ist_geloescht = 1
 WHERE schluessel IN ('heimresultate.aktionen', 'kantiresultate.aktionen');
