-- Migration 080: Hilfetexte zum Schutz ungespeicherter Eingaben und zur Werteprüfung (Okt 2026):
-- Rückfrage Speichern/Verwerfen/Zurück, «Nicht gespeichert» im Panelkopf, Fehlerliste statt Kappen,
-- Mitglieder: Enter springt ins nächste Feld.
--
-- Idempotent: ON DUPLICATE KEY UPDATE.
-- Hinweis: keine Zeile innerhalb der Strings darf mit zwei Bindestrichen beginnen (Kommentar-Filter des Runners).

INSERT INTO hilfetexte (schluessel, titel, inhalt_html, kategorie) VALUES
('endresultate.uebersicht',
 'Endschiessen: Resultate erfassen',
 '<p>Hier werden die Resultate der <strong>Mitglieder</strong> am Endschiessen erfasst. Die Tabelle zeigt für das gewählte Jahr alle Mitglieder, die Stiche gelöst oder bereits Resultate haben.</p><ul><li><strong>Zellen</strong>: eine Zahl ist das erfasste Resultat, «gelöst» (gelb) heisst bezahlt, aber noch kein Resultat, «–» heisst nicht gelöst. Bei Schwini steht «gelöst P1» oder «gelöst P2», wenn nur eine Passe gelöst ist.</li><li><strong>Stand</strong>: «offen» (Zeile gelb), solange ein gelöster Stich noch kein Resultat hat, sonst «vollständig». Oben steht, wie viele Mitglieder vollständig erfasst sind.</li><li><strong>Filter und Suche</strong>: «Offen» zeigt nur, was noch zu tun ist; die Suche filtert nach Namen.</li><li><strong>Zeile anklicken</strong> (oder mit den Pfeiltasten wählen und Enter) öffnet rechts das Erfassungs-Panel. Aktiv sind nur die gelösten Stiche; nicht gelöste sind zusammengeklappt.</li><li><strong>Werte</strong>: Endstich und Schwini pro Schuss 0–10, Kunst, Glück und Zabig als Hunderterwertung 0–100. Die Totale rechnen beim Tippen mit.</li><li><strong>Speichern &amp; nächstes offenes</strong> (auch Ctrl+Enter oder Enter im letzten Feld) speichert und öffnet das nächste Mitglied mit offenen Stichen. <strong>Speichern</strong> (Ctrl+S) speichert und schliesst das Panel. Schlägt das Speichern fehl, bleiben die Eingaben stehen.</li><li><strong>Prüfung</strong>: Werte ausserhalb des Bereichs oder keine Zahl werden rot markiert. Beim Speichern erscheint über den Knöpfen eine Liste, jeder Eintrag springt direkt ins Feld; gespeichert wird erst, wenn alle Werte stimmen.</li><li><strong>Nicht gespeichert</strong> steht im Panelkopf, solange Eingaben offen sind. Schliessen (Escape, Kreuz oder Klick daneben) und Blättern fragen dann: Speichern, Verwerfen oder Zurück.</li><li>Gespeichert wird ein Stich nur, wenn mindestens ein Wert grösser 0 ist.</li></ul><p>Der Papierkorb im Panel löscht die Resultate eines einzelnen Mitglieds. Ganze Jahre werden nicht gelöscht; frühere Jahre bleiben über die Jahresauswahl abrufbar. Resultate lassen sich auch aus der Imetron-CSV importieren (<a href="endsch_import.php">CSV-Import Endschiessen</a>); die Schüsse der Partnerinnen werden unter <a href="endresultate_partner.php">Partnerinnen erfassen</a> erfasst.</p>',
 'endresultate'),

('endresultate_partner.uebersicht',
 'Endschiessen: Partnerinnen erfassen',
 '<p>Hier werden die Resultate der <strong>Partnerinnen</strong> erfasst, die ein Mitglied ans Endschiessen mitbringt. Pro Mitglied und Jahr gibt es einen Eintrag mit Endstich, Sie-und-Er-Anteil und Partner Schwini.</p><ul><li><strong>Stand</strong>: «offen» (Zeile gelb), solange eine Partnerin noch keine Resultate hat, sonst «erfasst». Oben stehen Fortschritt und Zähler; Filter (Alle, Offen, Erfasst) und Suche grenzen die Liste ein.</li><li><strong>Gast</strong>: Gäste aus dem Lösen, für die noch kein Eintrag besteht, stehen mit der Marke «Gast» in der Liste. Ein Klick öffnet einen neuen Eintrag mit vorausgefülltem Namen; das Mitglied wird dazu gewählt.</li><li><strong>Partnerin hinzufügen</strong> öffnet ein leeres Panel: Mitglied wählen und Namen eingeben (beides Pflicht), Schüsse eintragen, speichern. Eine Zeile anklicken (oder mit den Pfeiltasten wählen und Enter) öffnet den bestehenden Eintrag.</li><li>Werte 0–10; beim Endstich und beim Partner Schwini sind Zehntel erlaubt, bei Sie und Er nur ganze Zahlen. Werte ausserhalb werden rot markiert und erst gespeichert, wenn sie korrigiert sind. Solange Eingaben offen sind, steht «Nicht gespeichert» im Panelkopf; Schliessen oder Blättern fragt dann nach.</li><li>In der Spalte «Sie und Er» stehen die Punkte der Partnerin rot und die des Mitglieds blau; die Schüsse des Mitglieds werden unter <a href="endresultate.php">Endschiessen Resultaterfassung</a> erfasst.</li><li><strong>Speichern &amp; nächste offene</strong> (auch Ctrl+Enter) speichert und öffnet die nächste Partnerin ohne Resultate, Ctrl+S speichert.</li></ul><p><strong>Löschen</strong> im Panel entfernt den ganzen Eintrag, also auch die Sie-und-Er-Schüsse 6–10 des Mitglieds. Ganze Jahre werden nicht gelöscht; frühere Jahre bleiben über die Jahresauswahl abrufbar. Ein Eintrag mit dem Namen «Partner» wurde vom Sie-und-Er-Erfassen oder vom CSV-Import als Platzhalter angelegt und wartet auf den richtigen Namen. Ranglisten: «Partner» und «Sie &amp; Er» unter <a href="endschrang.php">Endschiessen Ranglisten</a>.</p>',
 'endresultate_partner'),

('heimresultate.tabelle',
 'Raster: Eingabe, Stand und Total',
 '<ul><li>Pro Passe sind nur ganze Zahlen bis 100 erlaubt; ein grösserer Wert wird rot markiert, und gespeichert wird erst, wenn alle Werte stimmen. Die Liste über dem Raster führt direkt zum Feld. Ausgefüllte Felder sind weiss, leere grau.</li><li><strong>Enter</strong> oder <strong>Tab</strong> springt ins nächste Feld, die Pfeiltasten <strong>auf</strong> und <strong>ab</strong> in dieselbe Passe der Zeile darüber oder darunter. So lässt sich eine Passe für alle Schützen nacheinander eintragen.</li><li>Neben dem Namen steht, wie viele Passen erfasst sind (etwa 3/8, grün bei allen acht). Ein Klick auf den Namen öffnet den Schützen in der Schnellerfassung.</li><li><strong>Total</strong> ist die Summe aller Passen; die Rangliste rechnet dieselbe Summe.</li><li>Beim Speichern werden bei bestehenden Datensätzen nur ausgefüllte Felder übernommen. Ein geleertes Feld löscht den gespeicherten Wert nicht; wer ein Resultat entfernen will, trägt 0 ein.</li><li>Leere Felder vor einer später ausgefüllten Passe werden beim Speichern zu 0 (nicht geschossen). Mitglieder ohne einen einzigen Wert erhalten keinen Datensatz.</li><li>Ein ungültiger Wert verhindert das Speichern ganz: die Meldung nennt ihn, und es wird nichts geändert.</li></ul>',
 'heimresultate'),

('kantiresultate.tabelle',
 'Raster: Eingabe, Stand und Total',
 '<ul><li>Pro Passe sind nur ganze Zahlen bis 100 erlaubt; ein grösserer Wert wird rot markiert, und gespeichert wird erst, wenn alle Werte stimmen. Die Liste über dem Raster führt direkt zum Feld. Ausgefüllte Felder sind weiss, leere grau; die <strong>beste Passe</strong> eines Schützen ist blau hervorgehoben (in der Schnellerfassung mit «beste» beschriftet).</li><li><strong>Enter</strong> oder <strong>Tab</strong> springt ins nächste Feld, die Pfeiltasten <strong>auf</strong> und <strong>ab</strong> in dieselbe Passe der Zeile darüber oder darunter.</li><li>Neben dem Namen steht, wie viele Passen erfasst sind (etwa 2/5, grün bei allen fünf). Ein Klick auf den Namen öffnet den Schützen in der Schnellerfassung.</li><li><strong>Total</strong> ist die Summe aller Passen; die Rangliste rechnet dieselbe Summe.</li><li>Beim Speichern werden bei bestehenden Datensätzen nur ausgefüllte Felder übernommen. Ein geleertes Feld löscht den gespeicherten Wert nicht; wer ein Resultat entfernen will, trägt 0 ein.</li><li>Leere Felder vor einer später ausgefüllten Passe werden beim Speichern zu 0 (nicht geschossen). Mitglieder ohne einen einzigen Wert erhalten keinen Datensatz.</li><li>Ein ungültiger Wert verhindert das Speichern ganz: die Meldung nennt ihn, und es wird nichts geändert.</li></ul>',
 'kantiresultate'),

('mitgliederverwaltung.uebersicht',
 'Mitglieder verwalten',
 '<p>Die Stammliste aller Vereinsmitglieder mit Adresse, Kontakt, Sportgerät und Status. Ein Klick auf eine Zeile öffnet das Mitglied rechts zum Bearbeiten; <strong>gespeichert wird automatisch beim Schliessen</strong> des Panels (Escape) und beim Wechsel zu einem anderen Mitglied, mit Ctrl+S sofort; <strong>Enter</strong> springt ins nächste Feld. Die Zeile leuchtet kurz grün, wenn das Speichern geklappt hat.</p><ul><li><strong>Hinzufügen</strong>: Lizenznummer, Name, Vorname, Geburtsdatum und Waffe sind Pflicht. Die Lizenznummer muss frei sein.</li><li><strong>Import</strong>: CSV mit Semikolon im Format des CSV-Exports (Kopfzeile nötig). Bestehende Lizenznummern werden aktualisiert, neue angelegt; fehlerhafte Zeilen werden übersprungen und nach dem Import aufgelistet.</li><li><strong>CSV</strong> ist der vollständige Export (auch als Vorlage für den Import), <strong>Adressliste</strong> eine Excel-Datei ohne verstorbene Mitglieder.</li></ul><p>Die Mitgliederdaten werden überall weiterverwendet: in Ranglisten und Resultaterfassung, in der Einsatzplanung, für die Zuordnung von Portal-Logins (<a href="benutzerverwaltung.php">Benutzerverwaltung</a>) und in Exporten. <strong>Löschen ist endgültig</strong>; bei Austritten ist es meist besser, nur den Status «Aktiv» auszuschalten.</p>',
 'mitgliederverwaltung'),

('jmresultate.erfassung',
 'Erfassungs-Panel eines Anlasses',
 '<p>Im Kopf stehen Anlass, Maximalpunkte und, falls zutreffend, «2 Runden» (Sektionsmeisterschaft) und «Streicher». Darunter alle aktiven Mitglieder, alphabetisch in zwei Gruppen: <strong>Mit JM-Resultat</strong> (hat in diesem Jahr irgendwo ein gewertetes Resultat; Obligatorisch, Feldschiessen, Sektionsmeisterschaft und Cup zählen dafür nicht) und <strong>Noch ohne JM-Resultat</strong>. Ausgefüllte Felder sind weiss, leere grau; oben rechts steht, wie viele Mitglieder in diesem Anlass ein Resultat haben.</p><ul><li>Punkte als ganze Zahl eingeben. <strong>Enter</strong> springt zum nächsten Feld, im letzten Feld speichert Enter. Die Pfeiltasten <strong>auf</strong> und <strong>ab</strong> wechseln die Zeile. <strong>Ctrl+S</strong> speichert jederzeit. Das Suchfeld filtert die Liste.</li><li>Ein geleertes Feld löscht das Resultat beim Speichern.</li><li>Werte über den Maximalpunkten oder keine gültige Zahl werden rot umrandet; der Hinweis erscheint beim Zeigen oder Fokussieren des Feldes. Gespeichert wird erst, wenn alle Felder stimmen.</li><li><strong>Sektionsmeisterschaft</strong> hat zwei Felder R1 und R2; in der Rangliste zählt nur der höhere Wert.</li><li>Gelb hinterlegte Felder mit «gemeldet» stammen aus der Selbsteingabe im Portal. <strong>Speichern</strong> bestätigt alle Resultate dieses Anlasses, also auch diese Meldungen; sie deshalb vor dem Speichern prüfen.</li></ul><p>Escape, Abbrechen oder ein Klick neben das Panel schliessen es; bei ungespeicherten Eingaben (Hinweis «Nicht gespeichert» im Panelkopf) fragt die Seite: Speichern, Verwerfen oder Zurück. Unplausible Punkte (keine Zahl, nicht ganz, mehr als die Max-Punkte) listet die Seite über den Knöpfen auf; gespeichert wird erst, wenn alle stimmen. Schlägt das Speichern fehl, bleiben die Eingaben im Panel stehen.</p>',
 'jmresultate')

ON DUPLICATE KEY UPDATE
    titel         = VALUES(titel),
    inhalt_html   = VALUES(inhalt_html),
    kategorie     = VALUES(kategorie),
    ist_geloescht = 0;
